sources:
  - Kablammo.glyphs
buildOTF: True
buildTTF: False
axisOrder:
  - MORF
familyName: "Kablammo"
stat:
  - name: Morph
    tag: MORF
    values:
    - name: Zoink
      value: 0
    - name: Bloop
      value: 20
    - name: Splat
      value: 40
    - name: Eek
      value: 60